model_config:
  tokenizer_pretrained_model_name_or_path: google-bert/bert-base-uncased
  use_lora: false
  query_encoder_kwargs:
    model_name_or_path: google-bert/bert-base-uncased
    freeze_transformer: false
    embedding_representation: null
    base_encoder_output_dim: 768
    converter_kwargs:
      vector_dimensions: [768, 768, 768, 768, 768, 768, 768, 1]
      activation_type: relu
      do_residual_on_last: false
  passage_encoder_kwargs:
    model_name_or_path: google-bert/bert-base-uncased
    freeze_transformer: false
    pooling_type: cls
  shared_encoder: true
  loss_type:
    - margin_mse
    - cross_entropy
  loss_kwargs:
    - {}
    - {"use_in_batch_negatives": true, "only_use_first_item": true}

data_config:
  training_data_jsonl: data/triples.train.jsonl
  validation_data_jsonl: null
  positive_filter_type: first
  label_key: score
  num_positives_to_sample: 1
  num_negatives_to_sample: 7

trainer_config:
  hf_trainer_config:
    output_dir: ./checkpoints/hypencoder.6_layer_full_real_opt
    overwrite_output_dir: true
    per_device_train_batch_size: 64  
    per_device_eval_batch_size: 64
    gradient_accumulation_steps: 1
    learning_rate: 2.0e-05
    num_train_epochs: 10
    max_steps: 250000       
    save_strategy: steps
    save_steps: 5000        
    save_total_limit: 10
    logging_steps: 50
    bf16: true
    tf32: true
    fp16: false
    torch_compile: true     
    save_safetensors: false
    ddp_find_unused_parameters: true
    dataloader_num_workers: 8
    report_to: "tensorboard"
    run_name: "hypencoder_6_layer_full_real_opt"
  resume_from_checkpoint: true
